"""
Django settings for FiloArts project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(ecargokdyinudcqa29)!fk&e42856*nxvopl2v5_e6k@qil7b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
APPEND_SLASH = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'FiloArtsPlus'
]

JAZZMIN_SETTINGS = {
    "site_logo": "assets/img/logo.png",
    "login-logo": None,
    "custom_css": "admin/css/custom_admin.css",  # Load custom styles
    "site_icon": "assets/img/logo.png",
    "site_title": "FiloArts+ Admin",
    "site_header": "FiloArts+ Management",
    "site_brand": "FiloArts+",
    "site_brand_link": "/",  # Clickable Logo to Homepage
    "welcome_sign": "Welcome to FiloArts+ Admin Panel",
    "copyright": "FiloArts+ © 2025",

    "search_model": ["FiloArtsPlus.Drawing", "FiloArtsPlus.Client"],

    # ✅ Adding Home Button in Sidebar
    "topmenu_links": [
        {"name": "Home", "url": "/", "icon": "fas fa-home", "show_sidebar": True},
        {"model": "FiloArtsPlus.Drawing"},
        {"model": "FiloArtsPlus.Client"},
    ],

    "usermenu_links": [
        {"name": "Homepage", "url": "/", "new_window": False},  # Homepage Link in User Menu
    ],

    "icons": {
        "FiloArtsPlus.Drawing": "fas fa-paint-brush",
        "FiloArtsPlus.Client": "fas fa-users",
        "auth.User": "fas fa-user",
        "FiloArtsPlus.Transaction": "fas fa-credit-card",
    },

    # ✅ Controlling Sidebar Order
    "order_with_respect_to": [
        "Home",
        "FiloArtsPlus.Drawing",
        "FiloArtsPlus.Client",
        "FiloArtsPlus.Transaction",
    ],
}

MIDDLEWARE =  [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',



]

ROOT_URLCONF = 'FiloArts.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


WSGI_APPLICATION = 'FiloArts.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

import os

# URL for serving static files
STATIC_URL = "/static/"

# The directory where `collectstatic` will collect static files for deployment
STATIC_ROOT = os.path.join(BASE_DIR, "static/staticfiles")  # Ensure this is a valid path

# Additional static files directories (for development)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # Ensure this folder exists
]


LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/clients/'
SIGN_UP_URL = '/signup/'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
