# Generated by Django 5.1.3 on 2025-01-15 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiloArtsPlus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='filled_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
