# Generated by Django 5.1.3 on 2025-01-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiloArtsPlus', '0002_client_filled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_name', models.CharField(max_length=100)),
                ('drawing_artist', models.CharField(max_length=50)),
                ('drawing_price', models.IntegerField()),
                ('drawing_img', models.ImageField(upload_to='drawings/')),
            ],
        ),
    ]
