# Generated by Django 5.1.3 on 2025-02-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiloArtsPlus', '0005_alter_drawing_drawing_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password1', models.CharField(max_length=100)),
                ('user_password2', models.CharField(max_length=100)),
            ],
        ),
    ]
