# Generated by Django 5.1.3 on 2025-02-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FiloArtsPlus', '0006_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
