# Generated by Django 5.1.3 on 2025-03-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FiloArtsPlus', '0008_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
