# Generated by Django 5.1.3 on 2025-03-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiloArtsPlus', '0010_blog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='filled_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
