# Generated by Django 5.1.3 on 2025-03-19 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiloArtsPlus', '0012_remove_blog_author_remove_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='filled_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='filled_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
