# Generated by Django 5.1.3 on 2025-03-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FiloArtsPlus', '0013_remove_blog_post_date_blog_filled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post_date',
        ),
    ]
