# Generated by Django 5.1.3 on 2025-03-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiloArtsPlus', '0014_remove_blog_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='drawing_category',
            field=models.CharField(choices=[('pencil', 'Pencil Drawing'), ('charcoal', 'Charcoal Drawing'), ('watercolor', 'Watercolor Drawing')], default='pencil', max_length=20),
        ),
    ]
