# Generated by Django 5.1.3 on 2025-03-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiloArtsPlus', '0015_drawing_drawing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='drawing_category',
            field=models.CharField(choices=[('pencil', 'Pencil Drawings'), ('painting', 'Paintings'), ('penart', 'Pen Art')], max_length=20),
        ),
    ]
